### ISSUE TITLE
dequal is not a function

### ISSUE THREAD

**Issue by stolinski** [lukeed/dequal#13]
Just some super basic usage, getting an error saying that dequal isn't a function since the update to 2.0

`import dequal from 'dequal'`

```
function useDeepCompareMemoize(value) {
  const ref = React.useRef()

  if (!dequal(value, ref.current)) {
    ref.current = value
  }

  return ref.current
}
```

**Comment by lukeed** [comment]
Yes, there are breaking changes -- thats why it was 2.0.

You just have to do `import { dequal } from 'dequal'` now.
Please see the [2.0 release notes](https://github.com/lukeed/dequal/releases/tag/v2.0.0).

Hope that helps!

**Comment by stolinski** [comment]
Understood, I was just following the readme which still shows `import dequal from 'dequal';`  Looking at the readme is usually people's first step to looking for the current syntax.

**Comment by stolinski** [comment]
I was going to submit a pr for the readme, but looks like you've got it.

**Comment by lukeed** [comment]
I noticed that & just pushed a fix (f8443f5), thanks! :)

Btw Is there a dependent that sent you here, or was it your own  doing w/ my bad readme?

**Comment by stolinski** [comment]
It was just me. I updated, came to the read me to check the new implementation, hit the "bug".

**Comment by lukeed** [comment]
Ok 😄 Sorry for the mixup. That late-night-finish-line bit me

**Comment by stolinski** [comment]
NP, I know how it is. Thanks for the quick replys.
